config:

  # Simulation Parameters
  t-period: 0.3 # in secs
  seed: 1

  # IDM settings
  max-speed: 11.11 # in m/s
  local-view: 10 # in metres (one side)
  extended-view: 10 # in metres (one side)
  reg-size: 5 # in metres
  cell-size: 1 # in metres

  # Reward Function
  collision-penalty: 20
  nocomm-incentive: 0.1

  # UI settings
  render: false
  fps: 30

  # Frame Skip
  frame-skip-value: 1

  # Enable Traffic Lights
  enable-tf: true

  enable-lstm: false
  k-frames: 1