config:

  # Simulation Parameters
  t-period: 0.1 # in secs

  # IDM settings
  max-speed: 9 # in m/s
  local-view: 15 # in metres
  extended-view: 30 # in metres
  cell-size: 3 # in metres

  # UI settings
  render: true
  fps: 30


  