config:

  # Simulation Parameters
  t-period: 0.1 # in secs

  # IDM settings
  max-speed: 10 # in m/s
  local-view: 10 # in metres (one side)
  extended-view: 20 # in metres (one side)
  reg-size: 5 # in metres
  cell-size: 1 # in metres

  # UI settings
  render: true
  fps: 30


  