config:

  # Simulation Parameters
  t-period: 0.3 # in secs

  # IDM settings
  max-speed: 11.11 # in m/s
  local-view: 20 # in metres (one side)
  extended-view: 30 # in metres (one side)
  reg-size: 10 # in metres
  cell-size: 1 # in metres

  # Reward Function
  collision-penalty: -10
  comm-penalty: 0.2

  # UI settings
  render: true
  fps: 120

  # Frame Skip
  frame-skip-value: 1

  # Enable Traffic Lights
  enable-tf: true